### ISSUE TITLE
auro-avatar: BZE failing to load

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/auro-avatar#16]
## Describe the bug
![image](https://user-images.githubusercontent.com/7005799/142708231-930c2c9f-e0af-4c81-a876-f7a0d24c1cf8.png)

Was BZE loaded into the system before the destination fly date?

**Comment by gusnaughton** [comment]
How can we unit test to ensure that all ASpublished stations have avatars/fallbacks?

**Comment by blackfalcon** [comment]
We do not yet have fallback support. This issue was created, but never prioritized. 

- https://github.com/AlaskaAirlines/auro-avatar/issues/13

**Comment by gusnaughton** [comment]
This issue still persists. Do we have a way to update the BZE image to add it to our list? Who owns this process? I know Kayla Blyton was working with this, but I don't see any documentation here on how to maintain the citylist - how can I push the right image through myself?

**Comment by blackfalcon** [comment]
@gusnaughton I am not aware of anything I need to do in order to address this BZE issue? As you stated Kayla was on this in the past, but I haven't heard anything? From my perspective, all that needs to be done is an asset at the https://resource.alaskaair.net/-/media/Images/common-assets/destinations/ endpoint. 

That being said, the [previous comment](https://github.com/AlaskaAirlines/auro-avatar/issues/16#issuecomment-974570760) speaks to having a better fallback image. That is needed for sure!
